### PR TITLE
chore: switch from TravisCI to Github Actions

### PR DESCRIPTION
**Pull request by RyanZim**

### CODE REVIEW

**Review by mvayngrib — APPROVED** [review]
utACK

checks look good. I guess we dropped old node versions?

**Comment by RyanZim** [comment]
No, didn't drop them since I'm not immediately planning a major release: https://github.com/ExodusMovement/redux-watch/pull/19/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR11

**Review by mvayngrib — APPROVED** [review]
utACK

not sure how node 4 & 5 get tested now 🤔

**Comment by RyanZim** [comment]
I'm operating on the assumption that if it works on recent stuff and also on `0.10`, it'll work everywhere in between.

**Pull request merged**
