### PR TITLE
chore: update object-path ^0.9.2 to ^0.11.5

### PR DESCRIPTION
**Pull request by ChALkeR**
It includes some fixes for inherited properties.

### CODE REVIEW

**Comment by natalan** [comment]
@jprichardson heads up: this is High severity vulnerability. Please consider merging in and publishing an updated version of the module. https://www.npmjs.com/advisories/1573

**Comment by jprichardson** [comment]
Transferring this from @jprichardson to @exodusmovement. The team can handle it there.

**Comment by ChALkeR** [comment]
@natalan while `object-path` has a prototype pollution vuln on `set` method, it's not directly affecting the usage in this lib as only `get` is used: https://github.com/ExodusMovement/redux-watch/blob/1b978469fd2ebd97b63dec781062bf437eccaabb/index.js#L2

Should be updated though.

**Review by kklash — APPROVED** [review]

**Comment by ChALkeR** [comment]
Published 1.2.0.

**Comment by natalan** [comment]
@ChALkeR thanks!

**Pull request merged**
